///
/// Copyright 2026 the original author or authors.
///
/// Licensed under the Apache License, Version 2.0 (the "License");
/// you may not use this file except in compliance with the License.
/// You may obtain a copy of the License at
///
///      https://www.apache.org/licenses/LICENSE-2.0
///
/// Unless required by applicable law or agreed to in writing, software
/// distributed under the License is distributed on an "AS IS" BASIS,
/// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/// See the License for the specific language governing permissions and
/// limitations under the License.
///

/**
 * Builds a tiny, fully hand-assembled Helm chart `.tgz` (step 4b, RPS-294): one directory
 * `<name>/` holding `Chart.yaml` (rendered from `packages/helm/Chart.template.yaml`),
 * `values.yaml` and `e2e-marker.txt` (a random marker, so two publishes of one coordinate never
 * share content), packed with `docker-image.ts`'s own `buildTar` (a minimal ustar builder, no
 * `tar`/`tar-stream` dependency) then gzipped -- deliberately never `helm package`, the same
 * "own the exact bytes" reasoning as `docker-image.ts`'s/`nuget-raw.ts`'s file headers.
 * Confirmed live (H17): Helm 4.3.0's chart loader (`loader.Load`, used by both `helm push` and
 * the `cm-push` plugin) accepts this exact shape -- a single top-level directory named after the
 * chart, mtime-0 ustar headers, no pax extensions.
 *
 * Every tar entry name stays under one top-level `<name>/` directory (Helm's `loader/archive.go`
 * strips exactly one leading path segment and refuses any entry outside it), and `Chart.yaml`'s
 * `name` field must equal that directory name (the OCI manifest-push handler's `chartNameMismatch`
 * check, RPS-978, reads the parsed `Chart.yaml`'s own `name`, not the archive's directory).
 */
import { createHash } from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import zlib from 'node:zlib';

import mustache from 'mustache';

import { buildTar } from './docker-image.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const TEMPLATES_DIR = path.resolve(__dirname, '../packages/helm');

export interface BuiltChart {
  tgzBytes: Buffer;
  /** `sha256:<hex>` of the whole `.tgz` file -- what both `helm pull` (OCI) and `helm pull --repo`
   *  (classic) write to disk verbatim (see this file's header: never `helm package`). */
  tgzDigest: string;
  tgzDigestHex: string;
  chartYaml: string;
  name: string;
  version: string;
}

function sha256Hex(bytes: Buffer): string {
  return createHash('sha256').update(bytes).digest('hex');
}

/**
 * Renders `Chart.yaml` from the template, packs `<name>/Chart.yaml`, `<name>/values.yaml` and
 * `<name>/e2e-marker.txt` into a ustar tar (`buildTar`), then gzips it. `name`/`version` are
 * passed straight through into the template with triple-mustache (`{{{...}}}`, per this
 * project's own convention for a non-XML-parser-consuming template): both are generated by this
 * harness itself (`helm-raw.ts`'s `chartName`, `coordinates.ts`'s `boundedSemverVersion`) and
 * never come from outside input, so there is nothing here that needs escaping.
 */
export async function buildChart(opts: {
  name: string;
  version: string;
  marker: string;
}): Promise<BuiltChart> {
  const template = await fs.readFile(path.join(TEMPLATES_DIR, 'Chart.template.yaml'), 'utf8');
  const chartYaml = mustache.render(template, { name: opts.name, version: opts.version });

  const tar = buildTar([
    { name: `${opts.name}/Chart.yaml`, data: Buffer.from(chartYaml, 'utf8') },
    { name: `${opts.name}/values.yaml`, data: Buffer.from('replicaCount: 1\n', 'utf8') },
    { name: `${opts.name}/e2e-marker.txt`, data: Buffer.from(opts.marker, 'utf8') },
  ]);
  const tgzBytes = zlib.gzipSync(tar, { level: 6 });
  const hex = sha256Hex(tgzBytes);

  return {
    tgzBytes,
    tgzDigest: `sha256:${hex}`,
    tgzDigestHex: hex,
    chartYaml,
    name: opts.name,
    version: opts.version,
  };
}

/** Writes `built.tgzBytes` to `<dir>/<name>-<version>.tgz` -- a real `.tgz` FILE PATH, which every
 *  real client here needs (`helm push`/`helm cm-push`/`helm pull`'s own file layout), and returns
 *  that path. */
export async function writeChartFile(dir: string, built: BuiltChart): Promise<string> {
  await fs.mkdir(dir, { recursive: true });
  const file = path.join(dir, `${built.name}-${built.version}.tgz`);
  await fs.writeFile(file, built.tgzBytes);
  return file;
}
