///
/// Copyright 2026 the original author or authors.
///
/// Licensed under the Apache License, Version 2.0 (the "License");
/// you may not use this file except in compliance with the License.
/// You may obtain a copy of the License at
///
///      https://www.apache.org/licenses/LICENSE-2.0
///
/// Unless required by applicable law or agreed to in writing, software
/// distributed under the License is distributed on an "AS IS" BASIS,
/// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/// See the License for the specific language governing permissions and
/// limitations under the License.
///

/**
 * The stable `code` (Java `msgId`) an API error answers with. Each value is the spelling of the matching Java
 * error constant and is a client contract: never change a value here.
 */
export const ERROR_CODES = {
  ACCESS_DENIED: 'accessDenied',
  ACCESS_NOT_ALLOWED: 'accessNotAllowed',
  ARCHIVE_FILE_NAME_INVALID: 'archiveFileNameInvalid',
  ARCHIVE_VERSION_MISMATCH: 'archiveVersionMismatch',
  ARTIFACT_ID_TOO_LONG: 'artifactIdTooLong',
  ARTIFACT_NOT_FOUND: 'artifactNotFound',
  ARTIFACT_OVERRIDE_IS_PROHIBITED: 'artifactOverrideIsProhibited',
  ARTIFACT_SIGNATURE_NOT_VERIFIED: 'artifactSignatureNotVerified',
  ARTIFACT_SIGNING_KEY_NOT_REGISTERED: 'artifactSigningKeyNotRegistered',
  ARTIFACT_VERSION_NOT_FOUND: 'artifactVersionNotFound',
  BAD_VERSION_STRING: 'badVersionString',
  CHART_ALREADY_EXISTS: 'chartAlreadyExists',
  CHART_API_VERSION_INVALID: 'chartApiVersionInvalid',
  CHART_APP_VERSION_TOO_LONG: 'chartAppVersionTooLong',
  CHART_DEPENDENCIES_INVALID: 'chartDependenciesInvalid',
  CHART_NAME_INVALID: 'chartNameInvalid',
  CHART_NAME_MISSING: 'chartNameMissing',
  CHART_NAME_TOO_LONG: 'chartNameTooLong',
  CHART_NOT_FOUND: 'chartNotFound',
  CHART_TYPE_INVALID: 'chartTypeInvalid',
  CHART_VERSION_INVALID: 'chartVersionInvalid',
  CHART_VERSION_MISSING: 'chartVersionMissing',
  CHART_VERSION_TOO_LONG: 'chartVersionTooLong',
  CHART_YAML_INVALID: 'chartYamlInvalid',
  CHART_YAML_NOT_FOUND: 'chartYamlNotFound',
  CLEANUP_POLICY_DISABLED: 'cleanupPolicyDisabled',
  CRATE_NOT_FOUND: 'crateNotFound',
  CRATE_VERSION_NOT_FOUND: 'crateVersionNotFound',
  DEPLOY_TOKEN_NOT_REVOCABLE: 'deployTokenNotRevocable',
  DOWNLOAD_TOKEN_EXPIRED: 'downloadTokenExpired',
  ERROR_OCCURRED: 'errorOccurred',
  FILE_ALREADY_EXISTS: 'fileAlreadyExists',
  GEM_NOT_FOUND: 'gemNotFound',
  GEM_VERSION_ALREADY_EXISTS: 'gemVersionAlreadyExists',
  GEM_VERSION_ALREADY_YANKED: 'gemVersionAlreadyYanked',
  GEM_VERSION_NOT_FOUND: 'gemVersionNotFound',
  GO_MOD_MODULE_PATH_MISMATCH: 'goModModulePathMismatch',
  GO_MOD_NOT_FOUND_IN_ZIP: 'goModNotFoundInZip',
  GO_MODULE_VERSION_ALREADY_EXISTS: 'goModuleVersionAlreadyExists',
  GO_MODULE_ZIP_EMPTY: 'goModuleZipEmpty',
  GROUP_ID_TOO_LONG: 'groupIdTooLong',
  GROUP_NOT_FOUND: 'groupNotFound',
  HELM_CHART_EMPTY: 'helmChartEmpty',
  IMAGE_NOT_FOUND: 'imageNotFound',
  INVALID_ARTIFACT_PATH: 'invalidArtifactPath',
  INVALID_CREDENTIALS: 'invalidCredentials',
  INVALID_GEM_FILE: 'invalidGemFile',
  INVALID_MODULE_VERSION: 'invalidModuleVersion',
  INVALID_PACKAGE_VERSION: 'invalidPackageVersion',
  INVALID_SEARCH_PARAMETER: 'invalidSearchParameter',
  INVALID_STORAGE_PATH: 'invalidStoragePath',
  ITEM_NOT_FOUND: 'itemNotFound',
  LAYER_NOT_FOUND: 'layerNotFound',
  LOGIN_REQUIRED: 'loginRequired',
  MALFORMED_POM_FILE: 'malformedPomFile',
  MANIFEST_CONTENT_TYPE_MISSING: 'manifestContentTypeMissing',
  MANIFEST_NOT_FOUND: 'manifestNotFound',
  MAVEN_FILE_NAME_TOO_LONG: 'mavenFileNameTooLong',
  MAVEN_METADATA_TOO_LARGE: 'mavenMetadataTooLarge',
  MAVEN_SIGNATURE_TOO_LARGE: 'mavenSignatureTooLarge',
  MAVEN_UPLOAD_BODY_EMPTY: 'mavenUploadBodyEmpty',
  MAVEN_VERSION_TOO_LONG: 'mavenVersionTooLong',
  MODULE_NOT_FOUND: 'moduleNotFound',
  MODULE_PATH_TOO_LONG: 'modulePathTooLong',
  MODULE_VERSION_TOO_LONG: 'moduleVersionTooLong',
  NPM_PUBLISH_BODY_EMPTY: 'npmPublishBodyEmpty',
  PACKAGE_NOT_FOUND: 'packageNotFound',
  PACKAGE_OVERRIDE_DISABLED: 'packageOverrideDisabled',
  PACKAGE_VERSION_ALREADY_EXISTS: 'packageVersionAlreadyExists',
  PACKAGE_VERSION_NOT_FOUND: 'packageVersionNotFound',
  PAYLOAD_TOO_LARGE: 'payloadTooLarge',
  PENDING_SIGNATURE_NOT_VERIFIED: 'pendingSignatureNotVerified',
  PGP_SETTINGS_UNSUPPORTED: 'pgpSettingsUnsupported',
  POM_FILE_TOO_LARGE: 'pomFileTooLarge',
  POM_GROUP_ID_MISMATCH: 'pomGroupIdMismatch',
  REFRESH_TOKEN_EXPIRED: 'refreshTokenExpired',
  RELEASE_NOT_FOUND: 'releaseNotFound',
  RELEASE_VERSIONS_ARE_PROHIBITED: 'releaseVersionsAreProhibited',
  RELEASES_SNAPSHOTS_UNSUPPORTED: 'releasesSnapshotsUnsupported',
  REPO_NOT_FOUND: 'repoNotFound',
  REPO_SCOPE_NOT_MATCHED: 'repoScopeNotMatched',
  RESOURCE_BUSY: 'resourceBusy',
  RESOURCE_NOT_FOUND: 'resourceNotFound',
  SESSION_EXPIRED: 'sessionExpired',
  SHA256_DIGEST_MISMATCH: 'sha256DigestMismatch',
  SHA256_DIGEST_MISSING: 'sha256DigestMissing',
  SHA256_MISMATCH: 'sha256Mismatch',
  SNAPSHOT_VERSIONS_ARE_PROHIBITED: 'snapshotVersionsAreProhibited',
  TAG_NOT_FOUND: 'tagNotFound',
  TOO_MANY_REQUESTS: 'tooManyRequests',
  UN_AUTHORIZED: 'unAuthorized',
  UNKNOWN_PATH: 'unknownPath',
  VALIDATION_ERROR: 'validationError',
  VERSION_NOT_FOUND: 'versionNotFound',
} as const;
