#!/bin/sh
# Copyright 2026 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Regenerates the API client (when it is out of date) and runs Playwright for one project. Calls the
# installed binaries directly (node_modules/.bin/...) rather than through "pnpm run"/"pnpm exec": the
# container runs as the host's uid:gid (docker-compose.runners.yml), not the root that built
# node_modules, and pnpm's own script runner re-verifies the modules directory against its store on
# every invocation, which fails under that uid mismatch even though the packages themselves only need
# to be read.
#
# REPSY_E2E_OPENAPI_SPEC and REPSY_E2E_GEN_OUT (RPS-1500) name the OpenAPI spec the client is generated
# from and the directory it goes to, so a runner of another repository (Repsy Cloud's) generates ITS
# client. The defaults are Repsy OS's own; both are relative to the working directory (/app), where the
# harness itself is.
#
# The output directory sits in a bind mount that every runner of the checkout shares, and several runners
# start at once (a `run.sh test --protocol a,b` run after run, two agents on one machine, RPS-1468). So the
# generation is safe to run concurrently:
#   - it is skipped when the client is current: "$out/.stamp" holds the sha256 of the spec, the version of
#     openapi-typescript-codegen and the generator's arguments, and a matching stamp means nothing to do;
#   - otherwise it takes an exclusive lock ("$out.lock", flock), re-checks the stamp (the runner that held
#     the lock may just have generated it), generates into "$out.tmp.<pid>" and only then swaps it into
#     place, so no runner ever reads a half-written directory and no runner deletes what another reads.
# "entrypoint.sh --gen-api [--force]" only does that step (`pnpm gen:api` is that call with --force).
set -eu

spec="${REPSY_E2E_OPENAPI_SPEC:-../repsy-backend/src/main/resources/openapi/openapi-spec.yaml}"
out="${REPSY_E2E_GEN_OUT:-src/api/generated}"

# The generator's arguments, one place: they are part of the stamp, so changing one regenerates.
GEN_ARGS="--client axios --name PanelClient --useOptions --indent 2"

sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | cut -d' ' -f1
  else
    shasum -a 256 "$1" | cut -d' ' -f1
  fi
}

wanted_stamp() {
  codegen="$(sed -n 's/^ *"version": *"\([^"]*\)".*/\1/p' ./node_modules/openapi-typescript-codegen/package.json | head -n 1)"
  printf 'spec=%s codegen=%s args=%s' "$(sha256_of "$spec")" "$codegen" "$GEN_ARGS"
}

is_current() {
  [ -f "$out/.stamp" ] && [ "$(cat "$out/.stamp")" = "$1" ]
}

# The generation proper, called with the lock held (when flock exists).
generate_locked() {
  stamp="$1"
  force="$2"
  if [ "$force" != "force" ] && is_current "$stamp"; then
    echo "API client in $out is current (generated by a runner that held the lock)"
    return 0
  fi
  # Leftovers of a runner that was killed mid-generation; nobody else generates while this holds the lock.
  rm -rf "$out".tmp.* "$out".old.*
  tmp="$out.tmp.$$"
  echo "Generating the API client from $spec into $out"
  # shellcheck disable=SC2086 # GEN_ARGS is a list of words
  ./node_modules/.bin/openapi --input "$spec" --output "$tmp" $GEN_ARGS
  printf '%s' "$stamp" > "$tmp/.stamp"
  if [ -e "$out" ]; then
    mv "$out" "$out.old.$$"
  fi
  mv "$tmp" "$out"
  rm -rf "$out.old.$$"
}

gen_api() {
  force="${1:-}"
  stamp="$(wanted_stamp)"
  if [ "$force" != "force" ] && is_current "$stamp"; then
    echo "API client in $out is current, not regenerated"
    return 0
  fi
  mkdir -p "$(dirname "$out")"
  if command -v flock >/dev/null 2>&1; then
    # fd 9 is the lock file, released when the subshell ends (flock is util-linux: in the runner images).
    (
      flock -w 300 9 || {
        echo "Timed out after 300 s waiting for the API client lock $out.lock" >&2
        exit 1
      }
      generate_locked "$stamp" "$force"
    ) 9> "$out.lock"
  else
    # No flock (a macOS host running `pnpm gen:api`): the temp directory and the swap still keep a
    # concurrent reader safe, only two generators may redo the work.
    generate_locked "$stamp" "$force"
  fi
}

if [ "${1:-}" = "--gen-api" ]; then
  if [ "${2:-}" = "--force" ]; then gen_api force; else gen_api; fi
  exit 0
fi

project="$1"
shift

gen_api

exec ./node_modules/.bin/playwright test --project="$project" "$@"
