/*
 * Copyright 2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.repsy.os.server.protocols.docker.protocol.handlers;

import static io.repsy.os.server.protocols.docker.protocol.handlers.DockerWire.bytes;
import static io.repsy.os.server.protocols.docker.protocol.handlers.DockerWire.imageManifest;
import static io.repsy.os.server.protocols.docker.protocol.handlers.DockerWire.index;
import static io.repsy.os.server.protocols.docker.protocol.handlers.DockerWire.sha256;
import static org.assertj.core.api.Assertions.assertThat;

import io.repsy.os.AbstractIntegrationTest;
import io.repsy.os.server.protocols.docker.shared.storage.services.DockerStorageService;
import io.repsy.os.server.protocols.docker.shared.tag.repositories.ManifestRepository;
import io.repsy.os.shared.auth.utils.PasswordHasher;
import io.repsy.os.shared.repo.entities.Repo;
import io.repsy.os.shared.repo.services.RepoTxService;
import io.repsy.os.shared.usage.services.UsageUpdateService;
import io.repsy.os.shared.user.entities.UserRole;
import io.repsy.protocols.shared.repo.dtos.RepoType;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Proxy;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.Callable;
import java.util.concurrent.CyclicBarrier;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicReference;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.config.BeanPostProcessor;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Import;
import org.springframework.mock.web.MockHttpServletResponse;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.context.WebApplicationContext;

/**
 * RPS-1314: two concurrent FIRST pushes of the same manifest into one image both find no {@code
 * docker_manifest} row and both insert; the loser fails on the {@code (image_id, digest)} unique
 * index at commit. The push handler runs the whole save transaction again, which then finds the row
 * the winner committed, so both clients get their {@code 201}.
 *
 * <p>The race is forced, not hoped for: both pushes are held at a barrier after they read "no row"
 * and before they flush, so both are certain to insert. Runs without a test transaction since both
 * pushes have to commit; it deletes the repo and the user it committed.
 */
@Transactional(propagation = Propagation.NOT_SUPPORTED)
@DisplayName("Concurrent first pushes of one manifest into one image (RPS-1314)")
@Import(DockerConcurrentFirstPushIT.ManifestSaveHook.class)
class DockerConcurrentFirstPushIT extends AbstractIntegrationTest {

  private static final String IMAGE = "app";
  private static final long TIMEOUT_SECONDS = 30;

  @Autowired private WebApplicationContext webApplicationContext;
  @Autowired private RepoTxService repoTxService;
  @Autowired private DockerStorageService dockerStorageService;
  @MockitoBean private UsageUpdateService usageUpdateService;

  private static final AtomicReference<Runnable> AFTER_MANIFEST_SAVE = new AtomicReference<>();

  /**
   * Runs {@link #AFTER_MANIFEST_SAVE} when {@code ManifestRepository.save} returns. A Spring Data
   * repository cannot be a {@code @MockitoSpyBean} (the spy would call an abstract method), so the
   * repository is wrapped in a plain proxy that calls through. {@code save} of a new manifest only
   * queues the insert (the id is generated by the application): the row reaches the database when
   * the persistence context flushes, after the hook has run.
   */
  @TestConfiguration(proxyBeanMethods = false)
  static class ManifestSaveHook {

    @Bean
    static BeanPostProcessor manifestSaveHookProcessor() {
      return new BeanPostProcessor() {
        @Override
        public Object postProcessAfterInitialization(final Object bean, final String beanName) {
          if (!(bean instanceof ManifestRepository)) {
            return bean;
          }

          return Proxy.newProxyInstance(
              ManifestRepository.class.getClassLoader(),
              new Class<?>[] {ManifestRepository.class},
              (proxy, method, args) -> {
                final Object result;
                try {
                  result = method.invoke(bean, args);
                } catch (final InvocationTargetException e) {
                  throw e.getCause();
                }

                final var hook = AFTER_MANIFEST_SAVE.get();
                if (hook != null && "save".equals(method.getName())) {
                  hook.run();
                }

                return result;
              });
        }
      };
    }
  }

  private final List<UUID> createdRepoIds = new ArrayList<>();
  private final List<UUID> createdUserIds = new ArrayList<>();

  private DockerWire wire;

  @BeforeEach
  void setUpWire() {
    final var info =
        this.userTxService.create(
            uniqueUsername("firstpush"), UserRole.ADMIN, PasswordHasher.hash(VALID_PASSWORD));
    this.createdUserIds.add(info.getId());
    final var user = this.userRepository.findById(info.getId()).orElseThrow();
    this.wire =
        new DockerWire(
            this.mockMvc,
            this.webApplicationContext,
            protocolPort(),
            this.protocolBearerTokenFor(user));
  }

  @AfterEach
  void deleteCommittedData() {
    this.createdRepoIds.forEach(
        id -> this.jdbcTemplate.update("delete from repo where id = ?", id));
    this.createdRepoIds.clear();
    this.deleteCommittedUsers(this.createdUserIds);
    this.createdUserIds.clear();
    AFTER_MANIFEST_SAVE.set(null);
  }

  private Repo dockerRepo() {
    final var name = uniqueRepoName("docker-first");
    final var created = this.repoTxService.createRepo(name, RepoType.DOCKER, false, null);
    this.createdRepoIds.add(created.getId());
    this.dockerStorageService.createRepo(created.getId());

    return this.repoRepository.findByName(name).orElseThrow();
  }

  /**
   * Makes the first two saves of a manifest wait for each other, after each has read "no row" and
   * before either has flushed, so both pushes are certain to insert. Later saves (the retry) pass.
   */
  private void holdTheFirstTwoSavesAtABarrier() {
    final var barrier = new CyclicBarrier(2);
    final var arrivals = new AtomicInteger();

    AFTER_MANIFEST_SAVE.set(
        () -> {
          if (arrivals.getAndIncrement() < 2) {
            try {
              barrier.await(TIMEOUT_SECONDS, TimeUnit.SECONDS);
            } catch (final Exception e) {
              throw new IllegalStateException("the two pushes did not meet", e);
            }
          }
        });
  }

  private List<MockHttpServletResponse> runConcurrently(
      final Callable<MockHttpServletResponse> first, final Callable<MockHttpServletResponse> second)
      throws Exception {

    final var pool = Executors.newFixedThreadPool(2);
    try {
      final var one = pool.submit(first);
      final var two = pool.submit(second);

      return List.of(
          one.get(TIMEOUT_SECONDS, TimeUnit.SECONDS), two.get(TIMEOUT_SECONDS, TimeUnit.SECONDS));
    } finally {
      pool.shutdownNow();
    }
  }

  private int count(final String sql, final Repo repo, final String digest) {
    final var count = this.jdbcTemplate.queryForObject(sql, Integer.class, repo.getId(), digest);

    return count == null ? 0 : count;
  }

  private int manifestRows(final Repo repo, final String digest) {
    return this.count(
        """
        select count(*) from docker_manifest m
          join docker_image i on i.id = m.image_id
        where i.repo_id = ? and m.digest = ?
        """,
        repo,
        digest);
  }

  private int tagRows(final Repo repo, final String digest) {
    return this.count(
        """
        select count(*) from docker_tag t
          join docker_image i on i.id = t.image_id
        where i.repo_id = ? and t.digest = ?
        """,
        repo,
        digest);
  }

  @Test
  @DisplayName("two first pushes of an image manifest under two tags both get 201, one row")
  void twoFirstPushesOfAnImageManifest() throws Exception {
    final var repo = this.dockerRepo();
    // The image exists already, so only the manifest is contested.
    this.wire.pushBlobsOf(repo, IMAGE, "layer-seed");
    assertThat(this.wire.putImage(repo, IMAGE, "seed", imageManifest("layer-seed")).getStatus())
        .isEqualTo(201);
    this.wire.pushBlobsOf(repo, IMAGE, "layer-contested");
    final var manifest = imageManifest("layer-contested");
    this.holdTheFirstTwoSavesAtABarrier();

    final var responses =
        this.runConcurrently(
            () -> this.wire.putImage(repo, IMAGE, "a", manifest),
            () -> this.wire.putImage(repo, IMAGE, "b", manifest));

    assertThat(responses)
        .as("the push that lost the race is retried, not answered with an error")
        .extracting(MockHttpServletResponse::getStatus)
        .containsExactly(201, 201);
    final var digest = sha256(bytes(manifest));
    assertThat(this.manifestRows(repo, digest)).isEqualTo(1);
    assertThat(this.tagRows(repo, digest)).isEqualTo(2);
  }

  @Test
  @DisplayName("two first pushes of an index under two tags both get 201, one row")
  void twoFirstPushesOfAnIndex() throws Exception {
    final var repo = this.dockerRepo();
    final var child = imageManifest("layer-child");
    this.wire.pushBlobsOf(repo, IMAGE, "layer-child");
    assertThat(this.wire.putImage(repo, IMAGE, sha256(bytes(child)), child).getStatus())
        .isEqualTo(201);
    final var indexJson = index(child);
    this.holdTheFirstTwoSavesAtABarrier();

    final var responses =
        this.runConcurrently(
            () -> this.wire.putManifest(repo, IMAGE, "a", DockerWire.OCI_INDEX, indexJson),
            () -> this.wire.putManifest(repo, IMAGE, "b", DockerWire.OCI_INDEX, indexJson));

    assertThat(responses)
        .as("the push that lost the race is retried, not answered with an error")
        .extracting(MockHttpServletResponse::getStatus)
        .containsExactly(201, 201);
    final var digest = sha256(bytes(indexJson));
    assertThat(this.manifestRows(repo, digest)).isEqualTo(1);
    assertThat(this.tagRows(repo, digest)).isEqualTo(2);
  }
}
